services:
  - type: web
    name: anticv
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    branch: main
    region: frankfurt
